jog_arm_server:
  simu: true # Whether the robot is started in simulation environment
  coll_check: false # Check collisions?
  cmd_in_topic:  jog_arm_server/left_arm/delta_jog_cmds
  cmd_frame:  l_ur5_arm_ee_link  # TF frame that incoming cmds are given in
  incoming_command_timeout:  5  # Stop jogging if X seconds elapse without a new cmd
  joint_topic:  joint_states
  move_group_name:  left_arm
  singularity_threshold:  5.5  # Slow down when the condition number hits this (close to singularity)
  hard_stop_singularity_threshold: 12. # Stop when the condition number hits this
  cmd_out_topic:  l_arm_controller/command
  planning_frame:  l_ur5_arm_base_link
  low_pass_filter_coeff:  2.  # Larger --> trust the filtered data more, trust the measurements less.
  pub_period:  0.008  # 1/Nominal publish rate [seconds]
  scale:
    linear:  1  # Max linear velocity. Meters per pub_period. Units is [m/s]
    rotational:  1  # Max angular velocity. Rads per pub_period. Units is [rad/s]
  # Publish boolean warnings to this topic
  warning_topic: jog_arm_server/warning
